#   _________________________________________________________
#  |   __   _   ____   _   _   _____   _     _   _    ___    |
#  |  |  \ | | |  __| | | / | |  _  | | |   | | | |  / _ \   |
#  |  | | \| | | |_   | |/ /  | | | | | |   | |_| | | |_| |  |
#  |  | |\ | | |  _|  |   <   | | | | | |    \   /  |  _  |  |
#  |  | | \  | | |__  | |\ \  | |_| | | |__   | |   | | | |  |
#  |  |_|  |_| |____| |_| \_| |_____| |_____| |_|   |_| |_|  |
#  |_________________________________________________________|
#

Reloaded: "&aConfig reloaded."
NoPermission: "&cYou do not have permission to execute this command."


Permissions:
  FlyPerm: plotfly.fly # Allows the player to fly on plots they have permissions.
  BypassPerm: plotfly.bypass # If there is someone with this permission, flights will not be opened/closed when entering or exiting the plot.
  CommandPerm: plotfly.command # Allows the player to use the /plotfly command. It is recommended that this permission not be given to the player.
  ReloadPerm: plotfly.reload # Allows the player to use the /plotfly reload command. It is recommended that this permission not be given to the player.

Settings:
  FlightEnabled: "&8[&aPlotFly&8] &7Flight Mode: &aEnabled"
  EnabledSoundEffect: "ENTITY_ENDER_DRAGON_FLAP" # Sound effect given when the player enters the plot.
  FlightDisabled: "&8[&aPlotFly&8] &7Flight Mode: &cDisabled"
  DisabledSoundEffect: "ENTITY_ENDER_DRAGON_FLAP" # Sound effect when the player exits the plot
  CommandActive: "&8[&aPlotFly&8] &7Now your flight mode will be active or inactive when you enter the plot." # /plotfly enable message
  CommandInactive: "&8[&aPlotFly&8] &7Your flight mode will no longer be active or inactive when you enter the plot." # /plotfly disable message
  PermissionCheckInterval: 6000 # 1 Minute = 60 * 20 = 1200 1 tick = 1/20th of a second, so 6000 ticks = 5 minutes

Title:
  TitleMessage: false # Is the title message on or off?
  EnabledMessage: "&8Flight mode &2enabled"
  DisabledMessage: "&8Flight mode &4disabled"
  FadeIn: 2 # How long do you want it to take to appear on screen?
  Stay: 10 # How long do you want it to take to stay on screen?
  FadeOut: 2 # How many seconds do you want it to take for the text to disappear from the screen?